version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course-hub-api
    restart: always
    environment:
      DATABASE_URL: "file:/app/prisma/dev.db"
    volumes:
      - sqlite_data:/app/prisma
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate deploy && npm start"

volumes:
  sqlite_data:
