export enum RepostErrorCode {
  MISSING_OR_INVALID_PARAMS = "MISSING_OR_INVALID_PARAMS",
  ORIGINAL_POST_NOT_FOUND = "ORIGINAL_POST_NOT_FOUND",
  YOU_CANNOT_REPOST_OWN_POST = "YOU_CANNOT_REPOST_OWN_POST",
  DAILY_POST_LIMIT_REACHED = "DAILY_POST_LIMIT_REACHED",
  YOU_ALREADY_REPOSTED = "YOU_ALREADY_REPOSTED",
}
