export enum FollowErrorCode {
  MISSING_OR_INVALID_PARAMS = "MISSING_OR_INVALID_PARAMS",
  YOU_CANNOT_FOLLOW_YOURSELF = "YOU_CANNOT_FOLLOW_YOURSELF",
  YOU_CANNOT_UNFOLLOW_OR_FOLLOW_YOURSELF = "YOU_CANNOT_UNFOLLOW_OR_FOLLOW_YOURSELF",
  FOLLOWER_NOT_FOUND = "FOLLOWER_NOT_FOUND",
  FOLLOWED_NOT_FOUND = "FOLLOWED_NOT_FOUND",
  ALREADY_FOLLOW_USER = "ALREADY_FOLLOW_USER",
  YOU_NOT_FOLLOW_USER = "YOU_NOT_FOLLOW_USER",
}
